### ISSUE TITLE
illegal hardware instruction 

### ISSUE THREAD

**Issue by text2sql** [mallahyari/drqa#3]
i am getting this error when running the backend "python main.py" -> "zsh: illegal hardware instruction  python main.py"

**Comment by mallahyari** [comment]
I am not sure exactly what the problem is. Have you set up the Qdrant either locally or Cloud before you run the `main.py`?

**Comment by text2sql** [comment]
I did not do anything specifically. I thought I need to make changes only if I want to run in the cloud. 
Other than two APIs in .env do I need to do anything else to run it locally?

**Comment by mallahyari** [comment]
You need to set up your Vector database to store and search through embeddings, Qdrant in this case. So you can use the cloud version and they have a free tier that you can set up and get API keys and enter in the .env file. If you would like to use Qdrant locally, you need to get the docker and run it locally. Then you can run the code.

**Comment by text2sql** [comment]
If I set up in qdrant cloud, do I need to change anything in the code?

**Comment by mallahyari** [comment]
When you set up qdrant, enter the host url, and api key in the.env file and run the code. Then you should be running the code without any issues.  You can read my code to see how qdrant is initialized.
