### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by imSrbh** [mallahyari/drqa#5]
@mallahyari @TommyNeeld 
the file is not being uploaded 

[Errno 2] No such file or directory: 'app/documents/MLAlgosForBMR.pdf'
INFO:     127.0.0.1:40424 - "POST /upload-file HTTP/1.1" 200 OK
query='What is the context of the uploaded file?'
Batches: 100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.48it/s]
=========== 2023-04-25 20:10:30,612 :: INFO :: HTTP Request: POST https://de63d5ae-7d26-42c0-9792-3d1799d1bab8.us-east-1-0.aws.cloud.qdrant.io:6333/collections/qa_collection/points/search "HTTP/2 200 OK"
 I don't know.
INFO:     127.0.0.1:55898 - "POST /query HTTP/1.1" 200 OK
107511
[Errno 2] No such file or directory: 'app/documents/MLAlgosForBMR.pdf'
INFO:     127.0.0.1:47812 - "POST /upload-file HTTP/1.1" 200 OK

**Comment by mallahyari** [comment]
If you see the "No such file or directory" error, it means the directory you're trying to upload the file doesnt exist. To make sure, create a folder first and then give the path of the folder to the code to see if error goes away.
