### ISSUE TITLE
can not upload any doc ...  Uncaught runtime errors:

### ISSUE THREAD

**Issue by jfergus73** [mallahyari/drqa#6]
can not upload any doc ...

Uncaught runtime errors:

ERROR
Network Error
AxiosError@http://localhost:3000/static/js/bundle.js:59585:27
handleError@http://localhost:3000/static/js/bundle.js:58974:77

**Comment by mallahyari** [comment]
This is too general to figure out exactly what the problem is. Did you check your server to see if it's running. If you get cannot upload doc it means your client can't talk to the server.

**Comment by mallahyari** [comment]
issue closed!
