### ISSUE TITLE
Uncaught runtime errors:

### ISSUE THREAD

**Issue by Agbeli** [mallahyari/drqa#7]
Solved now.

**Comment by mallahyari** [comment]
Give a little bit more context. It's very hard to figure out what the problem is from this image. Can you put the entire error?

**Comment by Agbeli** [comment]
Thanks for the quick response. Whenever I make a query I get this response in the terminal. 
![Screenshot from 2023-06-23 11-17-15](https://github.com/mallahyari/drqa/assets/40799080/8f655e2d-cc0a-479f-8628-1be282256a56)

Please, could you advise me on on how to handle this problem? Thanks

**Comment by Agbeli** [comment]
INFO:     127.0.0.1:47422 - "GET /upload-file HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:57098 - "GET /query HTTP/1.1" 405 Method Not Allowed

Here is the results whenever I want to upload/query.

**Comment by Agbeli** [comment]
My select file is not work for me.

**Comment by mallahyari** [comment]
Awesome.
