### ISSUE TITLE
Messages after running npm start 

### ISSUE THREAD

**Issue by Agbeli** [mallahyari/drqa#8]
src/components/chat/ChatInterface.tsx
  Line 2:18:  'Button' is defined but never used  @typescript-eslint/no-unused-vars
  Line 2:26:  'Box' is defined but never used     @typescript-eslint/no-unused-vars
  Line 2:31:  'Grid' is defined but never used    @typescript-eslint/no-unused-vars

src/components/fileDetails/FileDetails.tsx
  Line 6:3:  'CardActions' is defined but never used  @typescript-eslint/no-unused-vars
  Line 7:3:  'CardMedia' is defined but never used    @typescript-eslint/no-unused-vars
  Line 8:3:  'Button' is defined but never used       @typescript-eslint/no-unused-vars

src/components/uploader/fileUploader.tsx
  Line 2:8:    'axios' is defined but never used                             @typescript-eslint/no-unused-vars
  Line 3:3:    'AxiosError' is defined but never used                        @typescript-eslint/no-unused-vars
  Line 4:3:    'AxiosResponse' is defined but never used                     @typescript-eslint/no-unused-vars
  Line 5:3:    'AxiosRequestConfig' is defined but never used                @typescript-eslint/no-unused-vars
  Line 30:10:  'uploadedFile' is assigned a value but never used             @typescript-eslint/no-unused-vars
  Line 146:7:  'LinearProgressWithLabel' is assigned a value but never used  @typescript-eslint/no-unused-vars

**Comment by mallahyari** [comment]
These are just warning, since they have been defined but later not used in the code. So that's not an issue. I will clean up the code, so it won't show warnings.
