### ISSUE TITLE
Sharing localhost remotely

### ISSUE THREAD

**Issue by mtomic-quant** [mallahyari/drqa#9]
I am trying to share the localhost:3000 webpage remotely to other people using ngrok and similar tunnelling services. The webpage works, but I keep getting '400 bad request' error when I try and send a request (i.e. chat message). I tried some ways to fix this but did not succeed. Would you know if there is something in your implementation that is interfering with this?

**Comment by mallahyari** [comment]
There isn't anything in the implementation that interferes with what you're trying to do. It all depends on your own OS and configurations. That said, if you would like to share your content with others, use my app here:
https://castly.fly.dev/login
It allows you to chat with AI and curate your conversation and publish it publicly. In other words, it's a platform for creating various types of content from tutorials to blogs. It's in Beta mode, so it's free for now. Please note that it's under constant development. I am currently working on it to add more features and release it soon. Go give it a try and let me know what you think.
